### ISSUE TITLE
Some files (Alzheimer's, Crohn's diseases) have latin-1 encoded characters

### ISSUE THREAD

**Issue by Lipastomies** [FINNGEN/betamatch-ext-data#48]
Some files have characters that really blow up downstream analysis, since they're essentially broken. Files should be cleaned.

**Comment by Lipastomies** [comment]
To clarify: There seem to be some latin-1 encoded characters in the files that don't map well into utf-8 (or ascii). Python does not like this, so let's run the files through iconv before adding them to the repo:
```
iconv -c -f UTF8 -t LATIN1 input_file > output_file
```
alternatively let's choose some other encoding than utf-8 and use that if desirable.

**Comment by mkveerapen** [comment]
Thanks for the suggestion, Aarto! Reformatting these files to this format now :)

**Comment by mkveerapen** [comment]
Moved all the edited files to `editedFiles`directory. Are they okay now? If they are, I can move them out to data and remove the older files. @Lipastomies

**Comment by Lipastomies** [comment]
Those files seem great! 

One thing I noticed is that there are some .DS_Store-files littered around the repository, I'm guessing because of a wildcard git add? I'd rather we didn't have those.

In the future, you can set a global gitignore file to ignore them:
```
# create file .gitignore_global somewhere, and add .DS_Store in it 
git config --global core.excludesfile FILE_LOCATION/.gitignore_global
```
Other than that, keep up the good work!

**Comment by Lipastomies** [comment]
Looks great, I'll close this.
